import type { Metadata } from "next";
import { Figtree, Readex_Pro, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const readeax = Readex_Pro({
  variable: "--font-readeax",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});


const flink = localFont({
  src: "../../public/fonts/flink.otf",
  variable: "--font-flink",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${readeax.variable} ${roboto.variable} ${flink.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
